"""full models

Revision ID: 6f400c0f5e0d
Revises: 
Create Date: 2025-03-04 17:17:35.601441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f400c0f5e0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'score',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
