"""full models

Revision ID: cdb777045d04
Revises: 6f400c0f5e0d
Create Date: 2025-03-04 17:23:34.487249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdb777045d04'
down_revision: Union[str, None] = '6f400c0f5e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_type',
               existing_type=postgresql.ENUM('MULTIPLE_CHOICE', 'TRUE_FALSE', 'OPEN_ENDED', name='questiontype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tests', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=5),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'score',
               existing_type=sa.Float(precision=5),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('questions', 'question_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MULTIPLE_CHOICE', 'TRUE_FALSE', 'OPEN_ENDED', name='questiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###
